mutation userSignin($input: SigninInput!) {
  signin(input: $input) {
    jwt_token
  }
}
# @restql { "filter": "data.signin" }
# {
# @api {post} /user/signin Signin User
# @apiName Signin User
# @apiDescription A post request to /api/users/signin, with valid user credentials, returns a JWT Token for authorization of future requests.
# @apiGroup User
# 
# @apiParam {String} email Users unique email.
# @apiParam {String} password Users password.
# 
# @apiSuccess {Object} signup Signin Result.
# @apiSuccess {String} jwt_token JWT Token.
# }