service: cms

provider:
  name: aws
  runtime: nodejs10.x
  region: ${opt:region, self:custom.default.region}
  stage: ${opt:stage, env:STAGE, env:stage, self:custom.default.stage}
  timeout: 30
  memorySize: 512
  versionFunctions: true
  environment:
    NODE_ENV: production
    STAGE: v1

# package:
#   individually: true
#   include:
#     - ./public/**

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: POST
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  # - serverless-hooks-plugin
  #- serverless-domain-manager
  #- serverless-apigw-binary
  - serverless-s3-sync
  - serverless-prune-plugin
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-webpack

custom:
  default:
    region: eu-central-1
    stage: v1
  # apigwBinary:
  #   types:
  #     - image/png
  #     - image/*
  #     - '*/*'
  s3Sync:
    # A simple configuration for copying static assets
    - bucketName: '${env:S3_BUCKET}' # required
      bucketPrefix: '${env:STAGE}/' # optional
      localDir: public # required

  # customDomain:
  #   domainName: '${env:DOMAIN}'
  #   basePath: ''
  #   certificateName: '*.${env:DOMAIN}'
  #   stage: ${env:STAGE, opt:stage, self:custom.default.stage}
  #   createRoute53Record: true
  #   endpointType: 'regional'
  #   securityPolicy: tls_1_2
  #   apiType: rest

  # hooks:
  #   before:package:createDeploymentArtifacts:
  #     - npm run build
  #     #- sh server/hooks/create-introspection-cache.sh

  webpack:
    webpackConfig: ./webpack.serverless.js
    includeModules:
      forceInclude:
        - pg
        - deepmerge
        - vuex-persistedstate
        - isomorphic-fetch
        - vue
        - vue-router
        - vuex
        - vue-meta
        - secure-ls
      forceExclude:
        - mssql
        - mysql
        - mysql2
        - sqlite3
        - clean-webpack-plugin
        - copy-webpack-plugin
        - dotenv-webpack
        - html-webpack-plugin
        - koa-webpack-hot-middleware
        - mini-css-extract-plugin
        - optimize-css-assets-webpack-plugin
        - terser-webpack-plugin
        - vue-loader
        - webpack
        - webpack-merge
        - webpack-node-externals

  prune:
    automatic: true
    number: 3
